// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ruqqcjoejcvjhfjucrlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1cXFjam9lamN2amhmanVjcmxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0OTk1MzIsImV4cCI6MjA1OTA3NTUzMn0.KskC4hwNR_bbbk4RE-MmESVgXOj7515tpwS8XuCD9Zw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);